INSERT INTO dsa_topic (name, order_index, description, icon, color) VALUES
('Arrays & Hashing', 1, 'Basic arrays and hash map problems', '🧩', '#4ade80'),
('Sorting', 2, 'Sorting algorithms and techniques', '📊', '#60a5fa'),
('Two Pointers', 3, 'Problems solved using two pointers approach', '✌️', '#f472b6'),
('Sliding Window', 4, 'Dynamic window for sub-arrays or substrings', '🪟', '#fbbf24'),
('Binary Search', 5, 'Searching in sorted arrays', '🔍', '#a78bfa'),
('Strings', 6, 'String manipulation problems', '🔤', '#38bdf8'),
('Recursion', 7, 'Functions that call themselves', '🔁', '#c084fc'),
('Linked List', 8, 'Nodes and pointers', '🔗', '#f87171'),
('Stack & Queue', 9, 'LIFO and FIFO data structures', '🥞', '#fb923c'),
('Binary Trees', 10, 'Tree traversal and manipulation', '🌲', '#34d399'),
('BST', 11, 'Binary Search Trees', '🌳', '#10b981'),
('Heap / Priority Queue', 12, 'Min and max heaps', '🏔️', '#818cf8'),
('Graphs', 13, 'Nodes and edges', '🕸️', '#94a3b8'),
('Dynamic Programming', 14, 'Overlapping subproblems', '🧠', '#e879f9'),
('Greedy', 15, 'Local optimum to global optimum', '🤑', '#facc15'),
('Backtracking', 16, 'Explore all paths', '🔙', '#f87171'),
('Tries', 17, 'Prefix trees', '🌲', '#2dd4bf'),
('Bit Manipulation', 18, 'Bitwise operations', '0️⃣', '#9ca3af'),
('Intervals', 19, 'Overlapping intervals', '↔️', '#8b5cf6'),
('Math & Geometry', 20, 'Mathematical problems', '📐', '#f43f5e');
